server:
  port: 8080


spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/expense
    username: root
    password: Hunter@4343
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/**
        - id: admin-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/admin/**
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/transaction/**,/api/v1/savings/**,/api/v1/analytics/**,/api/v1/budget/**
        - id: goal-service
          uri: ${GOAL_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/goal/**,/api/v1/goals/**

logging:
  file:
    name: logs/app.log
  level:
    root: DEBUG