spring:
  application:
    name: goal-service
  datasource:
    url: jdbc:mysql://localhost:3306/expense
    username: root
    password: Hunter@4343
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: goal-service
      auto-offset-reset: earliest

server:
  port: 8083

logging:
  file:
    name: logs/app.log
  level:
    root: DEBUG

services:
  transaction:
    baseurl: http://localhost:8082/api/v1